#!/usr/bin/env python3
"""Build NUMBERS_LEDGER.md and numbers_flat.json from the authoritative JSONs.

The ledger records WHERE every number lives. It does not interpret anything.
Re-run after any analysis change:  python3 build_ledger.py
"""
import json, os, sys, math
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
E01 = 'experiments/01_image_test'
E02 = 'experiments/02_form_constant_generator'
E03 = 'experiments/03_l23_hardening'
SOURCES = [
    ('exp01.prereg',      f'{E01}/preregistration.json'),
    ('exp01.sdxl.report', f'{E01}/results-local/sdxl/analysis_report.json'),   # from the HF dataset
    ('exp01.sd35.report', f'{E01}/results-local/sd35/analysis_report.json'),
    ('exp02.prereg',      f'{E02}/preregistration.json'),
    ('exp02.report',      f'{E02}/results-local/report.json'),
    ('exp03.prereg',      f'{E03}/preregistration.json'),
    ('exp03b.prereg',     f'{E03}/preregistration_axes.json'),
    ('exp03.sdxl.report', f'{E03}/results-local/sdxl/l23_report_claude-qwen.json'),
    ('exp03.sd35.report', f'{E03}/results-local/sd35/l23_report_claude-qwen.json'),
    ('exp03.sdxl.report3judge', f'{E03}/results-local/sdxl/l23_report.json'),
    ('exp03.sd35.report3judge', f'{E03}/results-local/sd35/l23_report.json'),
    ('exp03.posthoc',     f'{E03}/posthoc_report.json'),
    ('exp03.sensitivity', f'{E03}/posthoc_sensitivity.json'),
    ('exp03b.axes',       f'{E03}/axes_report.json'),
    # added 2026-09-16 for the preprint
    ('exp03.sdxl.report7b', f'{E03}/results-local/sdxl/l23_report_claude-qwen7b.json'),  # pre-swap panel, regenerated from archive/
    ('exp03.sd35.report7b', f'{E03}/results-local/sd35/l23_report_claude-qwen7b.json'),
    ('exp03.sensitivity2', f'{E03}/posthoc_sensitivity2.json'),  # round 2, pre-specified 2026-09-17 (interaction, random slopes, cluster bootstrap, same-28 kappa)
    ('exp03.humanhuman',  f'{E03}/results-local/human_human_kappa.json'),   # second rater (2026-10-02), author vs rater2
    ('exp03.rater2judges', f'{E03}/results-local/rater2_vs_judges.json'),  # second rater vs each judge, 2026-10-02
    ('exp03.qpaths',      f'{E03}/posthoc_quality_paths.json'),  # post-hoc 2026-09-28: quality-component check cited in Limitations; the Figure 5 appendix was removed 2026-09-29
    ('fig3.data',         'paper/figures/fig3_data.json'),   # per-prompt distortion raw vs partial (make_figures.py)
    ('fig4.data',         'paper/figures/fig4_data.json'),   # judge screen non-zero fractions (make_figures.py)
]

def flatten(obj, prefix, out):
    if isinstance(obj, dict):
        for k, v in obj.items():
            flatten(v, f'{prefix}.{k}', out)
    elif isinstance(obj, list):
        if all(isinstance(x, (int, float)) and not isinstance(x, bool) for x in obj):
            for i, x in enumerate(obj):
                out.append((f'{prefix}[{i}]', x))
        else:
            for i, x in enumerate(obj):
                flatten(x, f'{prefix}[{i}]', out)
    elif isinstance(obj, bool):
        out.append((prefix, str(obj)))
    elif isinstance(obj, (int, float)):
        if isinstance(obj, float) and math.isnan(obj):
            out.append((prefix, 'nan'))
        else:
            out.append((prefix, obj))
    elif isinstance(obj, str):
        out.append((prefix, obj[:120]))

rows = []
missing = []
for name, rel in SOURCES:
    path = os.path.join(ROOT, rel)
    if not os.path.exists(path):
        missing.append((name, rel)); continue
    with open(path) as f:
        flatten(json.load(f), name, rows)

numeric = [(k, v) for k, v in rows if isinstance(v, (int, float))]
with open(os.path.join(ROOT, 'paper/numbers_flat.json'), 'w') as f:
    json.dump({k: v for k, v in numeric}, f, indent=0)

with open(os.path.join(ROOT, 'paper/NUMBERS_LEDGER.md'), 'w') as f:
    f.write('# Numbers ledger (generated by build_ledger.py; do not edit by hand)\n\n')
    f.write('Every number in `paper.md` must trace to a row here. Where this file and a JSON\n'
            'disagree, the JSON wins. This file records locations, not findings.\n\n')
    if missing:
        f.write('## Missing sources\n\n')
        for name, rel in missing:
            f.write(f'- `{name}`: `{rel}` not found\n')
        f.write('\n')
    f.write('## Sources\n\n')
    for name, rel in SOURCES:
        f.write(f'- `{name}` = `{rel}`\n')
    f.write('\n## Values\n\n| key | value |\n|---|---|\n')
    for k, v in rows:
        sv = f'{v:.6g}' if isinstance(v, float) else str(v)
        f.write(f'| `{k}` | {sv} |\n')
print(f'{len(rows)} rows ({len(numeric)} numeric); missing: {[m[0] for m in missing]}')
